## ----------------------------------------------------------- ##
## Don't touch the next line unless you know what you're doing.##
## ----------------------------------------------------------- ##

# Name of the module
LOCAL_NAME := cust_src/elua

# List of submodules which contain code we need to include in the final lib
LOCAL_MODULE_DEPENDS := \
                        cust_src/elua/libc \
                        cust_src/elua/lua \
                        cust_src/elua/shell \

# This is a top-level module
IS_TOP_LEVEL := yes

## ------------------------------------- ##
##  Do Not touch below this line         ##
## ------------------------------------- ##
include ${SOFT_WORKDIR}/platform/compilation/cust_rules.mk

